# Generated by Django 3.1.1 on 2020-09-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_code', models.CharField(max_length=80)),
                ('from_name', models.CharField(max_length=80)),
                ('to_code', models.CharField(max_length=80)),
                ('to_name', models.CharField(max_length=80)),
                ('exchange_rate', models.CharField(max_length=80)),
                ('bid', models.CharField(max_length=80)),
                ('ask', models.CharField(max_length=80)),
                ('nermeen', models.CharField(max_length=80)),
            ],
        ),
    ]
