# Generated by Django 3.1.1 on 2020-09-03 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='nermeen',
        ),
    ]
